// Task 4: Create a custom error class that extends the built-in Error class. Throw an instance of this custom error in a function and handle it using a try-catch block.

class CustomError extends Error {
    constructor(message) {
        super(message);
        this.name = 'CustomError';
    }
}

function throwCustomError() {
    try {
        throw new CustomError('This is a custom error');
    } catch (error) {
        console.log('Error caught:', error.message);
    }
}

throwCustomError();
